[package]
name = "zero2prod"
version = "0.1.0"
authors = ["LukeMathWalker <rust@lpalmieri.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# Following the community convention, if `name` is unspecified,
# cargo will default to `package.name`, which is what we want.
# We could specify a library name using the `name` field.
path = "src/lib.rs"

# A project can only have one library, but it can have multiple
# binaries, specified as an array in double brakets [[]]
# To manage multiple libraries in the same repository
# have a look at the workspace feature - Covered later on.
[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
serde = "1.0.115"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
sqlx = { version = "0.5.1", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
uuid = { version = "0.8.1", features = ["v4"] }
chrono = "0.4.15"
tracing = "0.1.19"
tracing-futures = "0.2.4"
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.1.6"
tracing-log = "0.1.1"
serde-aux = "1.0.1"
tracing-actix-web = "0.4.0-beta.4"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
actix-rt = "2"
tokio = "1"
once_cell = "1.7.2"
