# configuration.yaml
application_port: 8000
database:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  # password: "password" # Docker
  password: QETJhP4Kfa9zoc8tTo*W3XEe # Local
  database_name: 'newsletter'
